# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='order_number',
            field=models.CharField(default='SO-602616', max_length=20, unique=True),
        ),
    ]
