# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=12)),
                ('prod_sku', models.CharField(max_length=100)),
                ('prod_img', models.ImageField(blank=True, upload_to='images')),
                ('prod_desc', models.CharField(max_length=200)),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=63)),
            ],
        ),
    ]
