# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160803_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_img',
            field=models.URLField(default='http://placehold.it/50x50'),
        ),
    ]
